### ISSUE TITLE
[ Feature ] - API 연결, 화면 수정, 추가

### ISSUE THREAD

**Issue by YeongHyeonHeo** [SMU-2024-Capstone/front-end#32]
## 계획된 개발 기능
API 연결, 화면 수정, 추가

## 기능 구현 세부사항
API 연결, 화면 수정, 추가

## 참고사항
없음

## Todo
- [ ] 북마크 화면 개발
- [ ] 마이페이지 화면 개발
- [ ] 커뮤니티 화면 개발
- [ ] 화면 수정
- [ ] api 코드 수정
